# Web服务器端口
server:
  port: 8080
  servlet:
    context-path: /es_cms

spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/es_cms?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
  # 配置spring-boot devtools
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**

# 配置mybatis mapper.xml文件
mybatis-plus:
  mapper-locations: classpath:mapper/es_cms/*.xml
